apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webserver
  name: webserver
  namespace: ontwikkel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver
    spec:
      containers:
      - image: facturen-api:v1
        name: facturen-api
        resources: {}
        ports:
          - containerPort: 5001
      - image: debiteuren-api:v1
        name: debiteuren-api
        resources: {}
        ports:
          - containerPort: 5002
      - image: rekenmodule-api:v1
        name: rekenmodule-api
        resources: {}
        ports:
          - containerPort: 5003
status: {}
